# -*- coding: utf-8 -*-
import os,sys
sys.path.insert(0,os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from core.data.rarity_manager import get_rarity_manager
from core.data.equipment_manager import get_equipment_manager, EquipmentManager
from core.data.research_manager import get_research_manager
from core.data.equipment_updater import add_research_phase_equipment
p=0;f2=0
def ck(d,o):
 global p,f2
 if o: p+=1;print("  PASS: "+d)
 else: f2+=1;print("  FAIL: "+d)
def sec(t):
 s="="*58;print("\n"+s+"\n  "+t+"\n"+s)
sec("1. RarityManager")
rmgr=get_rarity_manager()
ck("5 rarities",len(rmgr.get_all())==5)
r5=rmgr.get_by_id(5)
ck("get_by_id(5) ok",r5 is not None)
ck("name check",r5["name"]=="海上传奇")
ck("color check",r5["color_hex"]=="#FF69B4")
r4=rmgr.get_by_name("超稀有")
ck("get_by_name ok",r4 is not None)
ck("sr id=4",r4["rarity_id"]==4)
ck("id999=None",rmgr.get_by_id(999)is None)
sec("2. EquipmentManager query")
em=get_equipment_manager()
ck("14 items",len(em.get_all())==14)
ck("first=S1-001",em.get_all()[0]["equipment_id"]=="S1-001")
ck("no img field","image_path"not in em.get_all()[0])
eq=em.get_by_id("S1-001")
ck("get_by_id ok",eq is not None)
ck("rid=5",eq["rarity_id"]==5)
ck("type ok",eq["type"]=="战列炮")
pa=EquipmentManager.parse_research_id(eq["equipment_id"])
ck("phase=1 via ID",pa is not None and pa[0]==1)
ck("get_by_name ok",em.get_by_name("试作型三联装152mm主炮Mk17")is not None)
ck("search406=1",len(em.search_by_name("406mm"))==1)
ck("rarity5=5",len(em.get_by_rarity_id(5))==5)
ck("zhanlie=5",len(em.get_by_type("战列炮"))==5)
ck("phase1=2",len(em.get_by_phase(1))==2)
ck("research=12",len(em.get_research_equipment())==12)
ck("general=2",len(em.get_general_equipment())==2)
sec("3. ID tools")
ck("parse S1-001=(1,1)",EquipmentManager.parse_research_id("S1-001")==(1,1))
ck("parse S7-006=(7,6)",EquipmentManager.parse_research_id("S7-006")==(7,6))
ck("parse 123=None",EquipmentManager.parse_research_id("123")is None)
ck("make S1-001",EquipmentManager.make_research_id(1,1)=="S1-001")
ck("make S7-003",EquipmentManager.make_research_id(7,3)=="S7-003")
sec("4. Rarity enrich")
eqr=em.get_with_rarity_name(em.get_by_id("S1-001"))
ck("rarity_name ok",eqr["rarity_name"]=="海上传奇")
ck("rarity_color ok",eqr["rarity_color"]=="#FF69B4")
sec("5. Image mapping")
ck("set img",em.set_image_path("S1-001","img/t.png"))
ck("get img",em.get_image_path("S1-001")=="img/t.png")
ck("bad id",not em.set_image_path("NO","x.png"))
eqi=em.get_equipment_with_image()
ck("12+image_path",len(eqi)==14 and eqi[0].get("image_path")is not None)
em.set_image_path("S1-001","")
sec("6. CRUD")
r=em.add_equipment({"name":"__T1__","rarity_id":3,"type":"x","research_phase":0})
ck("add ok",r)
t=em.get_by_name("__T1__");tid=t["equipment_id"]
ck("num id",tid.isdigit())
ck("rename",em.update_equipment(tid,{"name":"__T1X__"}))
ck("new name",em.get_by_id(tid)["name"]=="__T1X__")
ck("chg rarity",em.update_equipment(tid,{"rarity_id":4}))
ck("rarity=4",em.get_by_id(tid)["rarity_id"]==4)
ck("delete",em.delete_equipment(tid))
ck("gone",em.get_by_id(tid)is None)
ck("no dup",not em.add_equipment({"name":"试作型三联装406mm主炮Mk6","rarity_id":5,"type":"x","research_phase":1}))
ck("bad rarity",not em.add_equipment({"name":"__T2__","rarity_id":999,"type":"x","research_phase":0}))
ck("empty name",not em.add_equipment({"name":"","rarity_id":3,"type":"x","research_phase":0}))
sec("7. Batch import")
r=em.import_equipment_batch([{"name":"__B1__","rarity_id":3,"type":"x","research_phase":0},{"name":"__B2__","rarity_id":3,"type":"x","research_phase":0},{"name":"试作型三联装406mm主炮Mk6","rarity_id":5,"type":"x","research_phase":1}])
ck("total=3",r["total"]==3)
ck("added=2",r["added"]==2)
ck("skipped=1",r["skipped"]==1)
for n in["__B1__","__B2__"]:
 e=em.get_by_name(n)
 if e:em.delete_equipment(e["equipment_id"])
sec("8. Statistics")
s=em.get_statistics()
ck("total=14",s["total"]==14)
ck("rainbow=5",s["by_rarity"].get("海上传奇")==5)
sec("9. ResearchManager")
rm=get_research_manager()
ck("6 phases",len(rm.get_all())==6)
ck("no luck","luck_benchmark"not in rm.get_all()[0])
p1=rm.get_by_phase(1)
ck("phase1 ok",p1 is not None)
ck("equip list",p1["equipment_list"]=="S1-001,S1-002")
eqs=rm.get_phase_equipment(1)
ck("2 items",len(eqs)==2)
ck("has rname",all(e.get("rarity_name")for e in eqs))
ck("count=2",rm.get_phase_equipment_count(1)==2)
ck("count999=0",rm.get_phase_equipment_count(999)==0)
ck("add",rm.add_phase({"name":"__TP__","equipment_list":"S1-001"}))
num=[p for p in rm.get_all()if p["name"]=="__TP__"][0]["phase_number"]
ck("rename",rm.update_phase(num,{"name":"__TP2__"}))
ck("new name",rm.get_by_phase(num)["name"]=="__TP2__")
ck("delete",rm.delete_phase(num))
s2=rm.get_statistics()
ck("stats",s2["total_phases"]==6 and s2["total_equipment"]==12)
sec("10. EquipmentUpdater")
r3=add_research_phase_equipment(7,"PR7",[("A","t"),("B","t"),("C","t"),("D","t"),("E","t")],("F","t"))
ck("success",r3["success"])
ck("6 added",r3["added"]==6)
ex=["S7-001","S7-002","S7-003","S7-004","S7-005","S7-006"]
ck("IDs ok",r3["ids"]==ex)
ck("phase added",r3["phase_added"])
ck("phase7 has 6",len(rm.get_phase_equipment(7))==6)
ck("total=20",len(em.get_all())==20)
sec("11. Cleanup")
rm.delete_phase(7)
for i in range(1,7):
 em.delete_equipment("S7-"+str(i).zfill(3))
ck("back to 14",len(em.get_all())==14)
ck("back to 6",len(rm.get_all())==6)
sec("Results")
total=p+f2
print("Total: "+str(total)+" Passed: "+str(p)+" Failed: "+str(f2))
if f2==0:
 print("ALL TESTS PASSED")
else:
 print(str(f2)+" FAILURES")
